build: false

environment:
    PYTHON: "C:\\Python37"

    matrix:
        - MINGW_CONFIGURATIONS: "4.9@x86@dwarf2@posix"
        - MINGW_CONFIGURATIONS: "6@x86@dwarf2@posix"
        - MINGW_CONFIGURATIONS: "7@x86@dwarf2@posix"
        - MINGW_CONFIGURATIONS: "8@x86@dwarf2@posix"
        - MINGW_CONFIGURATIONS: "4.9@x86_64@seh@posix"
        - MINGW_CONFIGURATIONS: "6@x86_64@seh@posix"
        - MINGW_CONFIGURATIONS: "7@x86_64@seh@posix"
        - MINGW_CONFIGURATIONS: "8@x86_64@seh@posix"

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - choco.exe install --no-progress --yes make
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools bincrafters_package_tools
  - conan user # It creates the conan data directory

test_script:
  - python build.py
